baseURL = "https://panoskarabelas.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hermit-v2"

title = "Panos Karabelas"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true

[params.author]
  name = "Panos Karabelas"
  about = "Graphics and engine programming, some other things too"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # category = "categories" # Uncomment if you wish to use categories

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  themeColor = "#494f5c"
  homeSubtitle = "Late night coding"
  footerCopyright = ' &#183; <a href="/media/cv.pdf" target="_blank" rel="noopener">CV</a>'
  bgImg = "https://raw.githubusercontent.com/PanosK92/panoskarabelas/master/source/content/media/wallpaper.jpg"
  justifyContent = false
  relatedPosts = false
  code_copy_button = true

[services.googleAnalytics]
  id = "UA-171661183-1"

[services.disqus]
  shortname = "https-panoskarabelas-com"

[[params.socialLinks]]
  name = "twitter"
  url = "https://twitter.com/panoskarabelas1"

[[params.socialLinks]]
  name = "github"
  url = "https://github.com/PanosK92/SpartanEngine"

[[params.socialLinks]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/panoskarabelas/"

[[params.socialLinks]]
  name = "youtube"
  url = "https://www.youtube.com/user/MrKarabelas92"

[[params.socialLinks]]
  name = "facebook"
  url = "https://www.facebook.com/panos.karabelas92"

[[params.socialLinks]]
  name = "email"
  url = "mailto:panosconroe@hotmail.com"

[menu]

[[menu.main]]
  name = "Posts"
  url = "posts/"
  weight = 10

[[menu.main]]
  name = "Projects"
  url = "projects/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 30
