baseURL = "https://panoskarabelas.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hermit-v2"

title = "Panos Karabelas"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true

[params.author]
  name = "Panos Karabelas"
  about = "Following the voice of the universe"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # category = "categories" # Uncomment if you wish to use categories

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  themeColor = "#494f5c"
  homeSubtitle = "Following the voice of the universe"
  footerCopyright = ' &#183; <a href="/cv_replica.html" target="_blank" rel="noopener">CV</a>' # Adjust path if needed
  bgImg = "/images/wallpaper.jpg" # Local path if hosted
  justifyContent = false
  relatedPosts = false
  code_copy_button = true
  # textColor = "#ffffff" # Uncomment if needed for contrast

[services.googleAnalytics]
  id = "UA-171661183-1"

[services.disqus]
  shortname = "panoskarabelas" # Update with your actual Disqus shortname

[[params.socialLinks]]
  name = "twitter"
  url = "https://twitter.com/panoskarabelas1"

[[params.socialLinks]]
  name = "github"
  url = "https://github.com/PanosK92/SpartanEngine"

[[params.socialLinks]]
  name = "youtube"
  url = "https://www.youtube.com/@panos_karabelas"

[[params.socialLinks]]
  name = "email"
  url = "mailto:panosconroe@hotmail.com"

[menu]

[[menu.main]]
  name = "Podcast"
  url = "podcast/"
  weight = 10

[[menu.main]]
  name = "Spartan Engine"
  url = "https://github.com/PanosK92/SpartanEngine"
  weight = 20

[[menu.main]]
  name = "Posts"
  url = "blog/"
  weight = 30

[[menu.main]]
  name = "Experience"
  url = "projects/"
  weight = 50 # Swapped with About

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 40 # Swapped with Experience